# Generated by Django 3.2.8 on 2023-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('idlogro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
