# Generated by Django 3.2.8 on 2023-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
