# Generated by Django 3.2.8 on 2023-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_alter_logro_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
