# Generated by Django 3.2.8 on 2023-07-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0003_alter_logro_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logro',
            table='logros',
        ),
    ]
