# Generated by Django 3.2.8 on 2023-06-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identification',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
