# Generated by Django 3.2.8 on 2023-06-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('typerol', models.CharField(max_length=20)),
            ],
        ),
    ]
